package dev.typetype.downloader.config

data class AppConfig(
    val httpPort: Int,
    val dbUrl: String,
    val dbUser: String,
    val dbPassword: String,
    val dbPoolSize: Int,
    val dbMinIdle: Int,
    val redisHost: String,
    val redisPort: Int,
    val redisQueueKey: String,
    val maxConcurrentWorkers: Int,
    val uploadConcurrency: Int,
    val maxQueueSize: Long,
    val jobTtlSeconds: Long,
    val ytdlpBin: String,
    val ytdlpTimeoutSeconds: Long,
    val ytdlpConcurrentFragments: Int = 1,
    val ytdlpRetries: Int = 10,
    val ytdlpFragmentRetries: Int = 10,
    val ytdlpSocketTimeoutSeconds: Int = 30,
    val ytdlpHttpChunkSize: String = "",
    val ytdlpExternalDownloader: String = "",
    val ytdlpExternalDownloaderArgs: String = "",
    val audioPassthroughDefault: Boolean = false,
    val tokenCacheTtlSeconds: Long = 600,
    val enableTranscode: Boolean,
    val s3Endpoint: String,
    val s3Region: String,
    val s3Bucket: String,
    val s3AccessKey: String,
    val s3SecretKey: String,
    val s3ArtifactTtlSeconds: Long,
    val tokenServiceUrl: String,
)

object AppConfigLoader {
    fun load(): AppConfig = AppConfig(
        httpPort = env("HTTP_PORT", "18093").toInt(),
        dbUrl = env("DB_URL", "jdbc:postgresql://localhost:55432/typetype_downloader"),
        dbUser = env("DB_USER", "typetype"),
        dbPassword = env("DB_PASSWORD", "typetype"),
        dbPoolSize = env("DB_POOL_SIZE", "8").toInt(),
        dbMinIdle = env("DB_MIN_IDLE", "1").toInt(),
        redisHost = env("REDIS_HOST", "localhost"),
        redisPort = env("REDIS_PORT", "56379").toInt(),
        redisQueueKey = env("REDIS_QUEUE_KEY", "downloader:queue"),
        maxConcurrentWorkers = env("MAX_CONCURRENT_WORKERS", "2").toInt(),
        uploadConcurrency = env("UPLOAD_CONCURRENCY", "2").toInt(),
        maxQueueSize = env("MAX_QUEUE_SIZE", "100").toLong(),
        jobTtlSeconds = env("JOB_TTL_SECONDS", "600").toLong(),
        ytdlpBin = env("YTDLP_BIN", "yt-dlp"),
        ytdlpTimeoutSeconds = env("YTDLP_TIMEOUT_SECONDS", "120").toLong(),
        ytdlpConcurrentFragments = env("YTDLP_CONCURRENT_FRAGMENTS", "1").toInt(),
        ytdlpRetries = env("YTDLP_RETRIES", "10").toInt(),
        ytdlpFragmentRetries = env("YTDLP_FRAGMENT_RETRIES", "10").toInt(),
        ytdlpSocketTimeoutSeconds = env("YTDLP_SOCKET_TIMEOUT_SECONDS", "30").toInt(),
        ytdlpHttpChunkSize = env("YTDLP_HTTP_CHUNK_SIZE", ""),
        ytdlpExternalDownloader = env("YTDLP_EXTERNAL_DOWNLOADER", ""),
        ytdlpExternalDownloaderArgs = env("YTDLP_EXTERNAL_DOWNLOADER_ARGS", ""),
        audioPassthroughDefault = env("AUDIO_PASSTHROUGH_DEFAULT", "false").toBooleanStrictOrNull() ?: false,
        tokenCacheTtlSeconds = env("TOKEN_CACHE_TTL_SECONDS", "600").toLong(),
        enableTranscode = env("ENABLE_TRANSCODE", "false").toBooleanStrictOrNull() ?: false,
        s3Endpoint = env("S3_ENDPOINT", "http://localhost:3900"),
        s3Region = env("S3_REGION", "garage"),
        s3Bucket = env("S3_BUCKET", "typetype-downloads"),
        s3AccessKey = env("S3_ACCESS_KEY", "change-me"),
        s3SecretKey = env("S3_SECRET_KEY", "change-me"),
        s3ArtifactTtlSeconds = env("S3_ARTIFACT_TTL_SECONDS", "7200").toLong(),
        tokenServiceUrl = env("TOKEN_SERVICE_URL", "http://localhost:8081"),
    )

    private fun env(name: String, fallback: String): String =
        System.getenv(name)?.takeIf { it.isNotBlank() } ?: fallback
}
